#define RAW_PROTOCOL
enum RAW_COMMAND_ID
{
    RAW_COMMAND_GET_PROTOCOL_VERSION=0x01,
    RAW_COMMAND_ENABLE_KEY_EVENT_REPORT=0x02,
    RAW_COMMAND_DISABLE_KEY_EVENT_REPORT=0x03,
    RAW_COMMAND_HEARTBEAT_PING=0x04,
    RAW_COMMAND_CHANGE_COLOR=0x05,
    RAW_COMMAND_REPORT_KEY_EVENT=0xA0,
    RAW_COMMAND_UNDEFINED=0xff,
};

static bool key_event_report=false;

#define PROTOCOL_VERSION 0x02
#define SUCCESS 0x01
#define FAILED 0xff